dist: trusty   # Use Ubuntu 14.04 image (instead of 12.04)
language: r
sudo: false
r:
  - oldrel
  - release
  - devel

cache:
  directories:
  - $HOME/.local/share/renv
  - $TRAVIS_BUILD_DIR/renv/library
  packages: true

install:
  - Rscript -e "if (!requireNamespace('renv', quietly = TRUE)) install.packages('renv')"
  - Rscript -e "renv::restore()"

script:
  - R CMD build .
  - R CMD check *tar.gz

after_success:
  - Rscript -e "covr::codecov()"
