comment: false

codecov:
  token: a7c1be67-d644-4ea5-bc8f-2d241bd49236
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true
