name: test-workflow
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: write cml report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Metrics" > report.md
          cat metrics.txt >> report.md

          echo "## Plots" >> report.md
          cml-publish auc_plot.png --md >> report.md

          cml-send-comment report.md
